### ISSUE TITLE
installation error on Windows

### ISSUE THREAD

**Issue by saccohuo** [coldnew/hexo-renderer-org#1]
Environment: Windows 7 x64, node v6.10.0, npm v3.10.10, python 3.5.2 & python 2.7.8.

When I install the package with `npm install https://github.com/coldnew/hexo-renderer-org#coldnew --save`, I got the following error.
```
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python\python.EXE" is v3.5.2, which
is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\configure.js:454:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\emacs\blog\node_modules\termios
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~0.3.1 (node_modules\he
xo-generator-feed\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "termios" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! termios@0.1.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the termios@0.1.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the termios package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs termios
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls termios
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\emacs\blog\npm-debug.log
```
So I switch to python 2.7 with `npm install --python=python2.7 https://github.com/coldnew/hexo-renderer-org#coldnew --save`, but it did not work neither. Given the following error.
```
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\emacs\blog\node_modules\termios
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
hexo-site@0.0.0 c:\emacs\blog
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~0.3.1 (node_modules\he
xo-generator-feed\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
0.3.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--python=python2.7" "https://gith
ub.com/coldnew/hexo-renderer-org#coldnew" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! termios@0.1.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the termios@0.1.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the termios package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs termios
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls termios
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\emacs\blog\npm-debug.log
npm ERR! code 1
```
BTW, I can install successfully from [CodeFalling](https://github.com/CodeFalling/hexo-renderer-org)'s original repo with `npm install https://github.com/CodeFalling/hexo-renderer-org#emacs --save`.

**Comment by coldnew** [comment]
mmm...... I don't know how to solve this issue :(

Can you try to use [yarn](https://github.com/yarnpkg/yarn) instead ?

**Comment by coldnew** [comment]
@saccohuo I more suggest you use docker on Windows. I think the issue is due to [child_pty](https://github.com/Gottox/child_pty) not supported on windows.

However, I try many fake pty plugin for node.js, the  [child_pty](https://github.com/Gottox/child_pty)  is `the only one` which can make emacs use pseudo pty correctly.

May there's other pty port which can work under Windows, but still need more time to test it.

**Comment by saccohuo** [comment]
@coldnew Alright, I have not used Docker before,  so I will give it a try tomorrow.

**Comment by coldnew** [comment]
Or maybe `bash on windows`, if you use Windows 10.

Windows support is not high priority in my TODO list, sorry for that :S

**Comment by coldnew** [comment]
I retest the [pty.js](https://github.com/chjj/pty.js/), which is said that can work on Windows and used by [hyper](https://github.com/zeit/hyper/commit/7f29ead1d52d6ad79cf1839d51fba92120419ba6).

The problem is that, [pty.js](https://github.com/chjj/pty.js/) maybe lack xterm-color support so the unit-test will faild if I use emacs's buildin `tango` theme.

Here's the unittest result: (red: pty.js, green: what I expect)

<img width="1212" alt="screen shot 2017-03-05 at 12 43 35 am" src="https://cloud.githubusercontent.com/assets/39703/23580430/cb8b5d3e-013c-11e7-8e11-110b0a08e0c7.png">

You can find that the red one's color does not what `tango` theme should be, though [pty.js](https://github.com/chjj/pty.js/) can work on windows, it's not a good plugin for this case.

**Comment by coldnew** [comment]
@saccohuo Now I switch to pty.js, can you help me test on Windows ?

**Comment by saccohuo** [comment]
Sorry, I am in the bed now, it's too late here. I will try it tomorrow. Thanks for your effort.

**Comment by coldnew** [comment]
Sure, Sleep well! :)

**Comment by saccohuo** [comment]
I tried it with npm by `npm install --python=python2.7 https://github.com/coldnew/hexo-renderer-org#coldnew --save`, and it gave the error msg as followed.
```
> pty.js@0.3.1 install c:\emacs\blog\node_modules\pty.js
> node-gyp rebuild


c:\emacs\blog\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\P
rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-g
yp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: deps\winpty\winpty.gyp not found (cwd: c:\emacs\blog\node_modules\pty.js) w
hile loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\emacs\blog\node_modules\pty.js
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
hexo-site@0.0.0 c:\emacs\blog
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN enoent ENOENT: no such file or directory, open 'E:\Dropbox\myblog\node_
modules\cheerio\package.json'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "--python=python2.7" "https://gith
ub.com/coldnew/hexo-renderer-org#coldnew" "--save"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\emacs\blog\npm-debug.log
npm ERR! code 1
```
Then I tried with yarn by `yarn install`, and the error msgs are as follows.
```
[-/5] ⠂ waiting...
[2/5] ⠂ hexo-util
[5/5] ⠂ hexo-util
[4/5] ⠂ pty.js: gyp info spawn args   '-Goutput_dir=.' ]
error c:\emacs\blog\node_modules\pty.js: Command failed.
Exit code: 1
Command: C:\Windows\system32\cmd.exe
Arguments: /d /s /c node-gyp rebuild
Directory: c:\emacs\blog\node_modules\pty.js
Output:
c:\emacs\blog\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\P
rogram Files (x86)\Yarn\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-g
yp.js" rebuild )  else (node  rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.10.0 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\gy
p\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\emacs\\blog\\node_modules\\pty.js\\build\\config.gypi
',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files (x86)\\Yarn\\node_modules\\node-gyp\\ad
don.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.node-gyp\\6.10.0\\include\\nod
e\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.node-gyp\\6.10
.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files (x86)\\Yarn\\node_module
s\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\emacs\\blog\\node_modules\\pty.js',

gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\emacs\\blog\\node_modules\\pty.js\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: deps\winpty\winpty.gyp not found (cwd: c:\emacs\blog\node_modules\pty.js) w
hile loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\Yarn\node_mo
dules\node-gyp\lib\configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files (x86)\
\Yarn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\emacs\blog\node_modules\pty.js
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.
```

**Comment by coldnew** [comment]
@saccohuo Can you try again ? I switch to https://github.com/Tyriar/node-pty, which is said that has more windows support :S

**Comment by saccohuo** [comment]
@coldnew Yeah, it works well. The installation can be completed finally with `npm install https://github.com/coldnew/hexo-renderer-org#coldnew --save` or `yarn install` after add `"hexo-renderer-org": "git+https://github.com/coldnew/hexo-renderer-org.git#coldnew"` into the dependencies in `package.json`.

**Comment by coldnew** [comment]
@saccohuo  Nice :)  I update the package again to use  `node-tty` stable version (0.6.2).
