### ISSUE TITLE
Docker下用不了，是因为这个插件需要调用emacs命令吗？

### ISSUE THREAD

**Issue by geek41** [coldnew/hexo-renderer-org#70]
`hexo    | Error: spawn emacs ENOENT
hexo    |     at exports._errnoException (util.js:1020:11)
hexo    |     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
hexo    |     at onErrorNT (internal/child_process.js:376:16)
hexo    |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
hexo    |     at process._tickCallback (internal/process/next_tick.js:104:9)
hexo exited with code 1`

**Comment by yanboyang713** [comment]
@geek41 我也遇到了，相同的问题。你的这个问题解决了吗？
